export type AdminSection = "news" | "research" | "popup" | "about" | "settings";

export interface AdminContentRecord {
  id: string;
  slug?: string;
  title: string;
  publishedAt?: string;
  status?: "published" | "draft";
  imageUrl?: string;
  attachmentUrl?: string;
  views?: number;
  imageDisplay?: "banner" | "full";
  excerpt?: string;
  content?: string;
  author?: string;
  summary?: string;
  tableOfContents?: string;
  keywords?: string;
  researchType?: string;
  category1?: string;
  category2?: string;
  link?: string;
  active?: boolean;
  startsAt?: string;
  endsAt?: string;
  chairmanMessage?: string;
  chairmanImageUrl?: string;
  organizationIntroduction?: string;
  organizationImageUrl?: string;
  purpose?: string;
  vision?: string;
  siteName?: string;
  footerInformation?: string;
  email?: string;
  searchKeywords?: string;
  eventType?: string;
  heldAt?: string;
  thumbnailLabel?: string;
  protectedDetails?: string[];
}
